# Plugin engine settings.
Plugin:
  # Name(s) for the main plugin command.
  Command_Aliases: excellentenchants,eenchants
  # Plugin language config.
  #
  # In 'lang' folder there are configs for different languages with a format like 'messages_code.yml',
  # where 'code' is the language code which you specify here.
  #
  # To create a new language config, simply copy the default one and rename it to your language code.
  Language: en
  # Plugin prefix name.
  Name: ExcellentEnchants
  Prefix: '&e%plugin_name% &8» &7'

# General plugin settings.
General:
  # Settings for the plugin tasks.
  Tasks:
    Arrow_Trails:
      # Defines the ticks interval (20 ticks = 1 second) for the arrow particle effect spawning.
      Ticks_Interval: 1
  # Enchantment global settings.
  Enchantments:
    # List of disabled custom enchantments.
    # Use enchantment file names from the 'enchants' folder without the file extension.
    # For example, to disable 'Explosive Arrows' enchantment you have to add 'explosive_arrows' to this list.
    Disabled:
      - enchant_name
      - other_enchant
    # Here you can disable certain enchantments in certain worlds.
    Disabled_In_Worlds:
      # This is your world name with a list of disabled enchantments.
      # Enchantment names are the same as in the option above.
      # To disable all enchantments, use '*'.
      my_world:
        - '*'
      other_world:
        - 'enchant_name'
        - 'another_enchant'
    # Item settings.
    Item:
      # How many of custom enchantments the item can contain at the same time?
      Max_Custom_Enchants: 3
      # Set this to 'true' to make Sword enchantments apply on Axes.
      Axes_As_Swords: true
      # Set this to 'true' to make Bow enchantments apply on Crossbows.
      Crossbows_As_Bows: true
      # Set this to 'true' to make Chestplate enchantments apply on Elytras.
      Elytra_As_Chestplate: true
    # Non-player entity settings.
    Entity:
      # When enabled, enchantments with a passive effects (potion effects, regeneration, etc.)
      # will be applied to mobs as well (if they are wearing items with such enchantments).
      # Enabling this feature may cause performance issues.
      Passive_Enchants_Applied_To_Mobs: false
    # Enchantment description settings.
    Description:
      # When enabled, each custom enchantment will add a description in item lore.
      Enabled: true
      # Description format for the item lore.
      # Placeholders:
      # - %description% - Enchantment description.
      Format: '&8▸ %description%'
  # Settings to obtain enchants via Enchanting Table.
  Enchanting_Table:
    # Enable/Disable this way to obtain custom enchantments.
    Enabled: true
    Enchantments:
      # Max. amount of all (including vanilla) enchantments on the item, when no more enchantments will be added.
      Total_Maximum: 4
      # Chance that a custom enchantment will be added.
      Custom_Generation_Chance: 90.0
      # Min. amount of custom enchantments to be added.
      Custom_Minimum: 0
      # Max. amount of custom enchantments to be added.
      Custom_Maximum: 2
  # Settings to obtain enchantments via Villager Trades.
  Villagers:
    Enabled: true
    Enchantments:
      Total_Maximum: 4
      Custom_Generation_Chance: 70.0
      Custom_Minimum: 0
      Custom_Maximum: 2
  # Settings to obtain enchantments via Loot Chests in dungeons and other world's structures.
  Loot_Generation:
    Enabled: true
    Enchantments:
      Total_Maximum: 4
      Custom_Generation_Chance: 80.0
      Custom_Minimum: 0
      Custom_Maximum: 2
  # Settings to obtain enchantments via Fishing.
  Fishing:
    Enabled: true
    Enchantments:
      Total_Maximum: 4
      Custom_Generation_Chance: 70.0
      Custom_Minimum: 0
      Custom_Maximum: 2
  # Settings to generate enchantments on mob equipment on spawn.
  Mob_Spawning:
    Enabled: true
    Enchantments:
      Total_Maximum: 4
      Custom_Generation_Chance: 70.0
      Custom_Minimum: 0
      Custom_Maximum: 2

# Enchantment tiers.
# You can create as many tiers as you want.
Tiers:
  # Tier identifier. Must be unique.
  common:
    # Tier display name.
    Name: '&fCommon'
    # Tier color.
    Color: '&f'
    # Tier obtain chances.
    Obtain_Chance:
      ENCHANTING: 80.0
      VILLAGER: 80.0
      LOOT_GENERATION: 80.0
      FISHING: 80.0
      MOB_SPAWNING: 80.0
  rare:
    Name: '&aRare'
    Color: '&a'
    Obtain_Chance:
      ENCHANTING: 50.0
      VILLAGER: 50.0
      LOOT_GENERATION: 50.0
      FISHING: 50.0
      MOB_SPAWNING: 50.0
  exotic:
    Name: '&eExotic'
    Color: '&e'
    Obtain_Chance:
      ENCHANTING: 25.0
      VILLAGER: 25.0
      LOOT_GENERATION: 25.0
      FISHING: 25.0
      MOB_SPAWNING: 25.0
  legendary:
    Name: '&6Legendary'
    Color: '&6'
    Obtain_Chance:
      ENCHANTING: 10.0
      VILLAGER: 10.0
      LOOT_GENERATION: 10.0
      FISHING: 10.0
      MOB_SPAWNING: 10.0
  cursed:
    Name: '&cCursed'
    Color: '&c'
    Obtain_Chance:
      ENCHANTING: 7.0
      VILLAGER: 5.0
      LOOT_GENERATION: 7.0
      FISHING: 12.0
      MOB_SPAWNING: 0.0