---
name: Build the plugin
on: [ push ]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache maven repository
        id: cache-mvn
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5

      - name: Install Spigot 1.20.4
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.20.4
          remapped: true
          buildToolProvider: SpigotMC

      - name: Install Spigot 1.20.2
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.20.2
          remapped: true
          buildToolProvider: SpigotMC

      - name: Install Spigot 1.20.1
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.20.1
          remapped: true
          buildToolProvider: SpigotMC

      - name: Install Spigot 1.19.4
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.19.4
          remapped: true
          buildToolProvider: SpigotMC

      - name: Install Spigot 1.18.2
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.18.2
          remapped: true
          buildToolProvider: SpigotMC

      - name: Check out NexEngine
        uses: actions/checkout@v4
        with:
          repository: 'nulli0n/NexEngine-spigot'
          ref: 'v2.2.12-final'
          path: 'NexEngine'

      - name: Install NexEngine
        run: mvn install
        working-directory: ./NexEngine

  ci:
    runs-on: ubuntu-latest
    needs: [ install-dependencies ]
    strategy:
      matrix:
        spigot:
          - 1.20.4-R0.1-SNAPSHOT
          - 1.20.2-R0.1-SNAPSHOT
          - 1.20.1-R0.1-SNAPSHOT
          - 1.19.4-R0.1-SNAPSHOT
          - 1.18.2-R0.1-SNAPSHOT
    steps:
      - uses: actions/checkout@v4

      - name: Cache maven repository
        id: cache-mvn
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5

      - name: Package plugin
        run: mvn package -Dspigot.version=${{ matrix.spigot }}

  build:
    runs-on: ubuntu-latest
    needs: [ install-dependencies ]
    steps:
      - uses: actions/checkout@v4

      - name: Cache maven repository
        id: cache-mvn
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5

      - name: Package plugin
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExcellentEnchants
          path: target/*.jar